name: publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
     -master
jobs:
  publish:
    runs-on:windows-latest

    steps:
     - uses: actions/checkout@v4
     
     - name: Setup .NET SDK
       uses: actions/setup-dotnet@v3
       with:
         dotnet-version: '8.0.x'
         
    - name: Restore
      run: dotnet restore ./Estahub.sln
    - name: Build
      run: dotnet build ./Estahub.sln --configuration Release --no-restore
    - name: Publish
      run: dotnet publish ./Estahub.sln --configuration Release --no-build 
    
       
       
       
